heat_template_version: 2016-10-14
description: A simple auto scaling group without scaling
resources:
#
# The auto scaling group defines a number of servers
# (between 1 and 5, starting with the desired number of
# 2 servers)
#
  my_servers:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 2
      max_size: 5
      min_size: 1
      resource:
#
# Servers are configured to run a mindless CPU burner
#
        type: OS::Nova::Server
        properties:
          config_drive: true
          key_name: 'mykey1'
          image: 'cirros-0.3.4-x86_64-disk'
          flavor: 1
          networks:
            - network: private
          user_data_format: RAW
          user_data:
            get_file: /home/ubuntu/cpu.sh

